openapi: 3.0.0
info:
  version: 1.0.0
  title: Contact Book API
  description: |
    Це API для керування контактами користувача. Ви можете створювати, оновлювати, видаляти та переглядати контакти.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: Contacts
    description: Операції для роботи з контактами
  - name: Auth
    description: Авторизація та логін користувачів

servers:

  - url: https://nodejs-hw-mongodb-7-gti2.onrender.com

paths:
  /contacts:
    get:
      $ref: '../swagger/paths/get.yaml'
    post:
      $ref: '../swagger/paths/post.yaml'

  /contacts/{contactId}:
    get:
      $ref: '../swagger/paths/contactsId/get.yaml'
    patch:
      $ref: '../swagger/paths/contactsId/patch.yaml'
    delete:
      $ref: '../swagger/paths/contactsId/delete.yaml'

  /auth/google:
    get:
      tags:
        - Auth
      summary: Увійти через Google
      description: Ініціалізує логін через Google OAuth 2.0
      responses:
        '302':
          description: Редірект на Google OAuth

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer

  schemas:
    Contact:
      $ref: '../swagger/components/Contact.yaml'
    NewContact:
      $ref: '../swagger/components/NewContact.yaml'
    UpdateContact:
      $ref: '../swagger/components/UpdateContact.yaml'
