openapi: 3.0.0
info:
  version: 1.0.0
  title: Contact Book API
  description: |
    Це API для керування контактами користувача. Ви можете створювати, оновлювати, видаляти та переглядати контакти.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Contacts
    description: Операції для роботи з контактами
  - name: Auth
    description: Авторизація та логін користувачів
servers:
  - url: http://localhost:3001
  - url: https://nodejs-hw-mongodb-7-gti2.onrender.com
paths:
  /contacts:
    get:
      $ref: './paths/contacts/get.yaml'
    post:
      $ref: './paths/contacts/post.yaml'
  /contacts/{contactId}:
    get:
      $ref: './paths/contacts/{id}/get.yaml'
    patch:
      $ref: './paths/contacts/{id}/patch.yaml'
    delete:
      $ref: './paths/contacts/{id}/delete.yaml'
  /auth/google:
    get:
      $ref: './paths/auth/google.yaml'
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
  responses:
    '401':
      $ref: './components/responses/401.yaml'
  schemas:
    Contact:
      $ref: './components/schemas/Contact.yaml'
    NewContact:
      $ref: './components/schemas/NewContact.yaml'
    UpdateContact:
      $ref: './components/schemas/UpdateContact.yaml'
